server:
  listen: ":8080"
  max_requests: 1000
  max_requests_per_conn: 1000
deriv:
  endpoint: "wss://ws.derivws.com/websockets/v3"
otel:
  prometheus:
    listen: ":8081"
    path: "/metrics"
api_source:
  etcd:
    servers: "etcd:2379"
    prefix: "api::"
  path: "./runtime/api_config"
